services:
  - type: web
    name: student-service-request-system
    runtime: docker
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        sync: false
